[2024-07-08T09:41:45.407+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-08T09:41:45.426+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_coount.DAG7_branch manual__2024-07-08T09:41:42.593640+00:00 [queued]>
[2024-07-08T09:41:45.431+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_coount.DAG7_branch manual__2024-07-08T09:41:42.593640+00:00 [queued]>
[2024-07-08T09:41:45.432+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-07-08T09:41:45.441+0000] {taskinstance.py:2330} INFO - Executing <Task(BranchPythonOperator): DAG7_branch> on 2024-07-08 09:41:42.593640+00:00
[2024-07-08T09:41:45.448+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1385) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-08T09:41:45.449+0000] {standard_task_runner.py:63} INFO - Started process 1387 to run task
[2024-07-08T09:41:45.449+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dag_coount', 'DAG7_branch', 'manual__2024-07-08T09:41:42.593640+00:00', '--job-id', '48', '--raw', '--subdir', 'DAGS_FOLDER/master_bracnh.py', '--cfg-path', '/tmp/tmpti6c3tjx']
[2024-07-08T09:41:45.451+0000] {standard_task_runner.py:91} INFO - Job 48: Subtask DAG7_branch
[2024-07-08T09:41:45.491+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_coount.DAG7_branch manual__2024-07-08T09:41:42.593640+00:00 [running]> on host 0ffcb94bda06
[2024-07-08T09:41:45.549+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_coount' AIRFLOW_CTX_TASK_ID='DAG7_branch' AIRFLOW_CTX_EXECUTION_DATE='2024-07-08T09:41:42.593640+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-08T09:41:42.593640+00:00'
[2024-07-08T09:41:45.551+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-08T09:41:45.551+0000] {baseoperator.py:400} WARNING - BranchPythonOperator.execute cannot be called outside TaskInstance!
[2024-07-08T09:41:45.560+0000] {logging_mixin.py:188} INFO - The DAG DAG_6 was triggered 0 times today.
[2024-07-08T09:41:45.561+0000] {python.py:237} INFO - Done. Returned value was: ['trigger']
[2024-07-08T09:41:45.561+0000] {branch.py:36} INFO - Branch into ['trigger']
[2024-07-08T09:41:45.561+0000] {skipmixin.py:178} INFO - Following branch ['trigger']
[2024-07-08T09:41:45.589+0000] {skipmixin.py:246} INFO - Skipping tasks [('already_triggered', -1), ('skip', -1)]
[2024-07-08T09:41:45.608+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-08T09:41:45.622+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=dag_coount, task_id=DAG7_branch, run_id=manual__2024-07-08T09:41:42.593640+00:00, execution_date=20240708T094142, start_date=20240708T094145, end_date=20240708T094145
[2024-07-08T09:41:45.663+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-07-08T09:41:45.685+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-08T09:41:45.689+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
