[2024-07-08T10:47:05.876+0000] {scheduler_job_runner.py:769} ERROR - Executor reports task instance <TaskInstance: master_branch.DAG_5_branch manual__2024-07-08T10:46:25.957708+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
